services:
  - type: web
    name: did-i-cook-api
    env: docker
    branch: main
    repo: https://github.com/Angus-Sun/Did-I-Cook
    root: apps/api
    dockerfilePath: apps/api/Dockerfile
    plan: starter
    envVars:
      - key: GEMINI_API_KEY
        value: ""
      - key: GEMINI_API_KEY2
        value: ""
      - key: GEMINI_API_KEY3
        value: ""
      - key: GEMINI_API_KEY4
        value: ""
      - key: GEMINI_API_KEY5
        value: ""
      - key: OPENSEARCH_URL
        value: ""

  - type: worker
    name: did-i-cook-worker
    env: docker
    branch: main
    repo: https://github.com/Angus-Sun/Did-I-Cook
    root: apps/worker
    dockerfilePath: apps/worker/Dockerfile
    plan: starter
    envVars:
      - key: PINECONE_API_KEY
        value: ""
      - key: PINECONE_ENV
        value: ""
      - key: PINECONE_INDEX
        value: "did-i-cook"
      - key: OPENSEARCH_URL
        value: ""

